### ISSUE TITLE
Android - No new focusing

### ISSUE THREAD

**Issue by graphefruit** [manateeworks/phonegap-manateeworks-v3#4] opened 2017-03-22 14:09 UTC
Hello @manateeworks !
Is it possible to let the user decided which area should be focused while scanning?
The problem occures when the room is darker, on the normal camera app, the focus can be switched so the actual "image" will be brighten up, while scanning this isn't possible, just reposition the camera focus helps.

This results that sometimes the scanning is very dark and therefore the barcode cant be scanned.

Thanks
Graphefruit

**Comment by ghost** [comment] 2017-03-23 18:41
Hi Graphefruit,

We do not currently support such a feature. We have added it to the list of possible features for future releases but have no time frame as to when it could be implemented. 

Thanks for your continued support.

Regards,
Team Manatee

**Comment by lazyvlad** [comment] 2017-03-23 18:42
Hi @graphefruit,
This is currently not possible with our scanner. The feature is certainly doable,  though we are not sure when we can put it on our agenda.

**Comment by graphefruit** [comment] 2017-03-23 18:43
HI @manateeworks 

I understand this, but shouldn't you do an auto focus at least like on Windows Phone?
So this "error" shouldn't occure to often because of auto focusing the center?

Thanks
Graphefruit

**Comment by ghost** [comment] 2017-03-23 19:21
Hello,

Please describe the "error". Most barcode scanning occurs when the code is centered within the display, which is where autofocusing is centered by design.

Regards,
Team Manatee

**Comment by graphefruit** [comment] 2017-03-27 12:43
Hello @manateeworks ,

the problem with Android seems like fixed, looked like a phone/condition problem - Couldn't reproduce it today.

The problem with Windows you can see here: https://www.youtube.com/watch?v=PtwE3xL6wVU&feature=youtu.be

It takes a realy long time to change the orientation.

I'm using this version: 3.0.14

The Phone is: Microsoft Lumia 550, Windows 10 Mobile.
OS-Number: 10.0.14393.953


Thanks in advance
Grpahefruit

**Comment by graphefruit** [comment] 2017-03-27 12:48
Hello @manateeworks,

Another point: The result.type is not set on windows-phone when canceling with the back button:
result.type -> null
But its set on android with "Cancel".

Update:
Shouldn't be also the back event be overwritten?
On android the "backbutton" event isn't triggered, on windows you're triggering the "backbutton" event.
Or better said: on android you're catching / not firing, on windows you do - is there any logic behind this?

Actualy the app is listening to the backbutton event and goes back in history.
If you're on the first page and starting the scan and closing it by windows, the app closes, on android just the scan-overlay closes.

**Comment by graphefruit** [comment] 2017-03-27 13:31
Hello @manateeworks ,

I've found another very strange behavior.
Windows Phone: When you start scanning and tapping out of the app or the phone goes to standby, and you open the app up again, the scan closes it self - nothing bad until here - but if you want to start again - the scan cant be started again.
No error popup or something like this, the scan just doesn't execute.

You need to close the app completely and start again - then you can scan.

I've tried to attach Visual Studio and have a deeper look into this issue: If the debugger is attached this problem cant be reproduced. 
It looks like the whole object getting to "undefined"

Thanks again
Graphefruit

**Comment by graphefruit** [comment] 2017-03-30 07:14
Hello @manateeworks  
Could you already have a look into these issues?
If you need more details I'd be happy to provide them.
Best regards
Graphefruit

**Comment by ghost** [comment] 2017-03-30 16:05
Hi @graphefruit ,

We have looked into the points you've made.

1. **It takes a really long time to change the orientation.**

	-The camera capture and preview are implemented in JavaScript on the web side. Windows doesn't seem to support non-native implementation well, and this results in lower frame rate than hardware available (https://github.com/manateeworks/phonegap-manateeworks-v3#performance), which in turn, also affects all camera-dependent features, like change of orientation.
This varies between different devices, for example, on Lumia 640 application-level rotation occurs right after OS-level orientation change with almost no noticeable lag. On Lumia 950 XL however, there are some extra OS-level transformations occurring over the camera preview during the orientation change, that a developer has no control over. The only thing we can do is hide the preview until those transformations have completed. On Lumia 950 XL it usually takes close to one second.


2. **result.type is not set on windows-phone when canceling with the back button (its set on android with "Cancel".)**

	-Yes, the result.type field is not set on windows phone upon canceling with the back button. We can easily update this for result.type to be set to "Cancel" so it behaves the same as it does on android.


3. **Back button behavior: If you're on the first page and starting the scan and closing it by windows, the app closes, on android just the scan-overlay closes.**

	-On both android and windows, when scanning in full screen, pressing the back button closes the preview and takes you back to the starting page. When scanning in partial view,
	windows again displays the same behavior, whereas android does not. This is because the partial view on android is part of the main activity, and exiting from it would cause exiting from the application. (the full screen is in a separate activity so the back button takes you back to the main activity)


4. **When you start scanning and tapping out of the app or the phone goes to standby, and you open the app up again, the scan closes it self - nothing bad until here - but if you want to start again - the scan cant be started again.**


We will follow up on the last point.

Best regards,
Team Manatee

**Comment by ghost** [comment] 2017-03-31 11:27
Hi again,

We resolved the last issue, and committed it along with update for point 2.

Best regards,
Team Manatee

**Comment by funkyvisions** [comment] 2017-03-31 12:53
Manatee,

Could you elaborate on that last post?  I have been doing the following
```
document.addEventListener("resume", function(){
    mwbScanner.startScanning(...)
});
```
Is that no longer going to be required?  I was having this discussion on your bug reporting system with another developer.

**Comment by ghost** [comment] 2017-03-31 13:14
Hi @funkyvisions ,

We made a change in handling the 'pause' event - the scanner is stopped and all references are cleared which takes you back to the starting point of the application. After that, you can have any kind of handling for the 'resume' event, which we leave non-handled.

Regards,
Team Manatee

**Comment by graphefruit** [comment] 2017-04-03 14:21
Hello @manateeworks,

sorry for my late response.
Thanks at first for your feedback and clarification. 

Point 1: So you'll implement a change here for hiding the transition? On my side I think it will be difficulty to give a user a better experience.
Maybe you can get yourself the CPU-Power of the windows phone and make the decision inside your code to show or hide the transition?

Point 3: Can I change something here in the config? Or do it need to catch the back event myself and just overwirte it while inside the Windows-Application?

Point 2 & 4: Thanks for the fixes, just let me know when I can install the latest update via git.

Thanks so far
Graphefruit

**Comment by ghost** [comment] 2017-04-03 15:01
Hi @graphefruit ,

All the changes to the code have been updated on GitHub.

Point 1: hiding the transition has already been implemented. Some devices "have a need" for it if there are extra transformations, others don't.
Although it's not a general recommendation to change the src/windows/MWBarcodeScannerProxy.js file, you could alter the code on line 115

`var hideDuringUpdate = true;`

to false to see what is happening behind the scenes, how long it takes, and determine if there is a need to hide the preview in the interest of providing a better UX. (keep in mind that this varies on different devices)

Point 3: we already updated the code. Now the back button does the same on both windows and android, pressing it while in full screen takes you back to the starting screen, and pressing it while on the starting screen regardless of whether you have a partial scanner or not will take you out of the app back to the operating system.

We are glad to help,
Team Manatee

**Comment by graphefruit** [comment] 2017-04-04 07:24
I'll give it a try and give you more feedback on thursday / friday.
Greetings!

**Comment by graphefruit** [comment] 2017-04-11 08:39
Hello @manateeworks 
sorry I just could try it today.
I've removed the old barcodescanner with
cordova plugin remove...
and then did: 
cordova plugin add https://github.com/manateeworks/phonegap-manateeworks-v3.git

But the version stays at 0.14 and the errors are not fixed on my side.
Still sloppy device-turn and back button closes app.
Can you help me here?
Thanks
Graphefruit

**Comment by ghost** [comment] 2017-04-12 14:11
Hi @graphefruit ,

We tried the same steps, removing the plugin with
`cordova plugin remove manateeworks-barcodescanner-v3`
and later adding the plugin with
`cordova plugin add manateeworks-barcodescanner-v3`
all done while Visual Studio is not running, and that updates the plugin to the latest version with everything working as expected.

The version number wasn't updated into the plugin.xml, that's why you were getting 3.0.14 which we now updated to 3.0.20 but this shouldn't affect the code. Our guess is that there might be referenced copies of our plugin in your project, as well as interference from some additional plugins. At any rate, if you are still unable to get the updated solution working, you could try to search for copies of our plugin' files within your project and replace them with the ones you've just updated. Another approach would be to remove and re-add all plugins. The last case of course would be to make a new build.

Best regards,
Team Manatee

**Comment by graphefruit** [comment] 2017-04-12 14:17
Hi @manateeworks ,

thanks for your feedback.
I had no references open aswell.
I gonna try it again and give you feedback, but I can't provide it earlier then 24.04, I'll comment then here.

Thanks for your help!
Greetings
Graphefruit

**Comment by graphefruit** [comment] 2017-04-24 07:01
Hi @manateeworks,

I could test it again, and still having the same issue.
To clearify: The result.type is now ="Cancel" - Thanks working fine now.
The version is: manateeworks-barcodescanner-v3 3.0.22

But if I'm pressing the hardware back button the app closes cause of the not overwritten event.

I'm attaching in JavaScript like: `document.addEventListener("backbutton", onBack, false);`
While in scan mode, this event should not be fired, like in Android - here its working fine.

The rotation issue still exists like in the youtube video shown above.

Also I'm missing the screen square after a successfull scan (working on Android)

After I've added the new plugin I removed the whole windows platform and added it again, also I've removed the App on the Windows-Phone for maybe some cached data.

Hope you can help me here.

Thanks Graphefruit

**Closed as completed** 2017-05-24 12:33 UTC

**Comment by dhiakhabouchi** [comment] 2018-10-31 15:22
Hi @manateeworks ,

using this plugin with ionic 3 , when i add callback to startScanning method , the camera interface becomes blank.

Hope you can help me here.

**Comment by ghost** [comment] 2018-11-01 15:13
Hi @dhiakhabouchi ,

We re-tested and haven't found such an issue. Can you give us more details:
1. Which platform are you using?
2. Does this issue only happen when adding a callback? (i.e. everything works fine when using startScanning method without a callback)

and send us the code where you invoke startScanning with a callback.

Also, this issue has been closed, and the problems you're experiencing should be addressed separately. Please submit a ticked on https://cmbdn.cognex.com/ , and we can continue there.

Regards,
Team Manatee
